### ISSUE TITLE
Error message when URL does not exist

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#58]
When an API endpoint does not exist (e.g. http://api-dev.freme-project.eu/current/xyz) then the request gets redirected to the proxy-filter basic service. There it produces this exception:

```
ERROR   2016-07-12 16:07:48,245 [http-nio-8084-exec-1] eu.freme.common.exception.ExceptionHandlerService  - Request: http://localhost:8084/current/toxolbox/convert/manage raised 
eu.freme.common.exception.InternalServerErrorException
	at eu.freme.bservices.filter.proxy.ProxyController.doProxy(ProxyController.java:68)
	at eu.freme.bservices.filter.proxy.ProxyController.doPost(ProxyController.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

This is wrong for two reasons:

* The response code should be 404 and the message should be "The requested API endpoint does not exist"
* The request should not be redirected to the proxy controller but directly to the exception handler

**Comment by jnehring** [comment]
this has been fixed in another issue
