### ISSUE TITLE
[Pipelines] NullPointerException when parameters are empty

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#61]
This request

```
[
    {
        "method": "POST",
        "endpoint": "http://api-dev.freme-project.eu/current/toolbox/xslt-converter/documents/xliff20-to-html",
        "headers": {"content-type": "text/xml", "accept" : "text/html"},
        "body": "<xliff version='2.0' xmlns='urn:oasis:names:tc:xliff:document:2.0' srcLang='en' trgLang='fr'> <file id='f1'>  <unit id='u1'>   <segment>   <source>We very much welcome you in the city of Prague, a home of XML!</source>   </segment>  </unit> </file></xliff>"
    },
    {
      "method": "POST",   
    	"endpoint": "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents",   
        "parameters": {     
        	"language": "en" ,  
            "dataset": "dbpedia"  
        },
        "headers": {  
        	"content-type" : "text/html" , 
            "accept": "text/turtle"  
        }
    }
]
```

leads to InternalServerError and this log

```
ERROR   2016-07-14 09:54:56,881 [http-nio-8080-exec-1] eu.freme.bservices.controllers.pipelines.PipelinesController  - 
java.lang.NullPointerException
	at eu.freme.common.persistence.model.SerializedRequest.getInputMime(SerializedRequest.java:146)
	at eu.freme.bservices.controllers.pipelines.core.PipelineService.chain(PipelineService.java:65)
	at eu.freme.bservices.controllers.pipelines.PipelinesController.pipeline(PipelinesController.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by jnehring** [comment]
When the parameters where empty, then a hashmap was not initialized leading to the NullPointerException. I fixed the problem and now the request works.
