### ISSUE TITLE
[e-Link] broken unit test

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#80]
A unit test in e-Link causes unstable builds in Jenkins:

```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 23.05 sec <<< FAILURE! - in eu.freme.eservices.elink.LinkingControllerTest
testLinkingDocuments(eu.freme.eservices.elink.LinkingControllerTest)  Time elapsed: 2.802 sec  <<< FAILURE!
java.lang.AssertionError: expected:<200> but was:<400>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at eu.freme.eservices.elink.LinkingControllerTest.testLinkingDocuments(LinkingControllerTest.java:147)
```

@bgrusdt please find out what is wrong.

**Comment by ArneBinder** [comment]
Is this a duplicate of https://github.com/freme-project/e-services/issues/28?

**Comment by jnehring** [comment]
right this is a dublicate
